---
# tasks file for webserver
- name: Install the latest version of nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Template a file to /usr/share/nginx/html/index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
  tags:
    - html

- name: Template a file to /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
  notify:
    - Start and enabled nginx